name: documentation
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy-to-gh-pages:
        type: boolean
        description: Deploy the documentation built with mkdocs to GitHub pages?

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs

      - run: mkdocs build
        if: github.event.inputs.deploy-to-gh-pages == 'false'
      - uses: actions/upload-artifact@v4
        with:
          name: pharo-launcher-documentation
          path: site
        if: github.event.inputs.deploy-to-gh-pages == 'false'

      - run: mkdocs gh-deploy
        if: github.event.inputs.deploy-to-gh-pages == 'true'
