name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/CI.yml
      
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v3
        with:
            path: artifacts

      - name: Prepare upload
        run: |
            ls -R artifacts

      #- name: Create Release
      #  uses: softprops/action-gh-release@v1
      #  if: startsWith(github.ref, 'refs/tags/')
      #  with:
      #      files: